---
title: "OpenBiodiv Demo"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Connect to triple store

```{r}
graphdb = basic_triplestore_access(
  server_url = "http://graph.openbiodiv.net:7777",
  user = "dbuser",
  password = "public-access"
)
graphdb$repository = "obkms_i6"
```

## Create R Lookup Function

```{r}
p_query = 
"PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dwc: <http://rs.tdwg.org/dwc/terms/>
PREFIX openbiodiv: <http://openbiodiv.net/>
PREFIX dwciri: <http://rs.tdwg.org/dwc/iri/>
PREFIX pkm: <http://proton.semanticweb.org/protonkm#>
PREFIX fabio: <http://purl.org/spar/fabio/>
PREFIX po: <http://www.essepuntato.it/2008/12/pattern#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>

SELECT (SAMPLE(?name) AS ?name) (SAMPLE(?genus) AS ?genus) (SAMPLE(?title) AS ?title)

WHERE
{
  ?name rdfs:label %label ;
        rdf:type openbiodiv:LatinName .
  ?name dwciri:taxonRank ?rank .
  ?name dwc:genus ?genus.

  ?article po:contains/pkm:mentions ?name ;
           rdf:type fabio:JournalArticle ;
           dc:title ?title .
} GROUP BY ?article 
"

genus_lookup = query_factory(p_query = p_query, access_options = graphdb)
```

## Execute Query

```{r}
genus_lookup("\"Drosophila\"")
```

## BONUS

```{r}
library(taxize)
gnr_resolve(names = "\"Drosophila\"", fields = "all")
```
